### ISSUE TITLE
Make it work on jupyterhub

### ISSUE THREAD

**Issue by callumrollo** [callumrollo/erddaplogs#11]
Probably needs some path magic

`ERROR: file:///home/user/notebooks/erddaplogs does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.`

**Comment by mwengren** [comment]
My approach was to attempt to install the package in my JupyterHub environment via pip local path reference, which sometimes works if the required package metadata files (as listed in error message above) are present:

```
!pip install -e .
```
Hopefully, this shouldn't be a difficult fix.  Thanks!

**Comment by mwengren** [comment]
By adding a single cell at the top of the notebook with a local pip install:

```
!pip install -e .
```
 
I'm now able to run the notebook in an ordinary JupyterHub, presumably with the addition of the `pyproject.toml` file!  

Does this belong in the notebook or is it more something one should know to add only if necessary?  In other words, since I can't create my own conda environment based off of the `environment.yml` file in this JupyterHub, this is a workaround I know to do.

**Comment by callumrollo** [comment]
Glad to hear it's working! It could be that we added pyproject.toml and other files in some of the more recent PRs :D

**Comment by callumrollo** [comment]
Resolved!
